android.enableJetifier=true
android.useAndroidX=true
org.gradle.unsafe.configuration-cache=true
systemProp.file.encoding=utf-8
org.gradle.unsafe.configuration-cache-problems=warn
org.gradle.jvmargs=-Xmx4g \
  --add-opens jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED \
  --add-opens jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED \
  --add-opens jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
  --add-opens jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED
