package project.pipepipe.app.platform

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.flow.StateFlow
import project.pipepipe.app.PlaybackMode

data class SubtitleCue(
    val text: String,
    val line: Float? = null,
    val position: Float? = null
)

data class ResolutionInfo(
    val height: Int,
    val width: Int,
    val codec: String?,
    val frameRate: Float,
    val isSelected: Boolean,
    val isHdr: Boolean = false
)

data class SubtitleInfo(
    val language: String,
    val isSelected: Boolean,
    val isAutoGenerated: Boolean = false
)

data class AudioLanguageInfo(
    val language: String,
    val isDefault: Boolean,
    val isSelected: Boolean
)

interface PlatformMediaController {
    val scope: CoroutineScope
    val isPlaying: StateFlow<Boolean>
    val currentPosition: StateFlow<Long>
    val duration: StateFlow<Long>
    val playbackState: StateFlow<PlaybackState>
    val currentSubtitles: StateFlow<List<SubtitleCue>>
    val currentMediaItem: StateFlow<PlatformMediaItem?>
    val currentItemIndex: StateFlow<Int>
    val repeatMode: StateFlow<RepeatMode>
    val shuffleModeEnabled: StateFlow<Boolean>
    val playbackSpeed: StateFlow<Float>
    val playbackPitch: StateFlow<Float>
    val bufferedPosition: StateFlow<Long>
    val availableResolutions: StateFlow<List<ResolutionInfo>>
    val availableSubtitles: StateFlow<List<SubtitleInfo>>
    val availableAudioLanguages: StateFlow<List<AudioLanguageInfo>>
    val currentAudioLanguage: StateFlow<String>
    val nativePlayer: Any
    val supportsAutoResolution: Boolean
        get() = true

    fun getCurrentPositionRealtime(): Long
    fun play()
    fun pause()
    fun stop()
    fun prepare()
    fun seekTo(positionMs: Long)
    fun seekToItem(index: Int, positionMs: Long = 0)
    fun seekToPrevious()
    fun seekToNext()
    fun setQueue(items: List<PlatformMediaItem>, startIndex: Int)
    fun setRepeatMode(mode: RepeatMode)
    fun setShuffleModeEnabled(enabled: Boolean)
    fun setPlaybackParameters(speed: Float, pitch: Float)
    fun applyPlaybackMode(mode: PlaybackMode)
    fun selectResolution(resolution: ResolutionInfo)
    fun selectSubtitle(subtitle: SubtitleInfo)
    fun applyDefaultResolution(defaultResolution: String)
    fun clearResolutionOverride()
    fun selectAudioLanguage(language: String)
    fun disableSubtitles()
    fun stopService()
    fun syncQueueShuffle()
    fun syncQueueClear()
    fun syncQueueRemove(index: Int)
    fun syncQueueAppend(item: PlatformMediaItem)
    fun syncQueueMove(from: Int, to: Int)
}

enum class PlaybackState {
    IDLE,
    BUFFERING,
    READY,
    ENDED
}

enum class RepeatMode {
    OFF,
    ONE,
    ALL
}
